spring:
  application:
    name: spring-test-data
  profiles:
    active: '@spring.profiles.active@'

server:
  port: 8087

logging:
  level:
    root: info
  pattern:
    console: '%gray%d{yyyy-MM-dd HH:mm:ss.SSS}| %highlight(%-5level)|%-20.20thread{60}|%cyan(%-50.50logger{120})|[%X{traceId:-}/%X{spanId:-}]|%msg%n'

management:
  endpoints:
    web:
      exposure:
        include: metrics, prometheus, health